apiVersion: v1
entries:
  predixy-redis-proxy:
    - apiVersion: v2
      name: predixy-redis-proxy
      version: 0.1.0
      appVersion: "latest"
      description:  A Helm chart for deploying Predixy as a Redis proxy
      keywords:
        - predixy
        - redis
        - proxy
      home: https://github.com/vahidaghazadeh/predixy
      sources:
        - https://github.com/vahidaghazadeh/predixy
      maintainers:
        - name: vahid aghazadeh
          email: v.opsource@gmail.com
      urls:
        - https://github.com/vahidaghazadeh/predixy/archive/refs/tags/latest.tar.gz
      dependencies: []
      conditions: []
      icons:
        - https://example.com/icon.png
    - apiVersion: v2
      name: predixy-redis-proxy
      version: 1.1.0
      appVersion: "latest"
      description: A Helm chart for deploying Predixy Redis Proxy with updates and improvements
      keywords:
        - predixy
        - redis
        - proxy
      home: https://github.com/your-repo/predixy-redis-proxy
      sources:
        - https://github.com/your-repo/predixy-redis-proxy
      maintainers:
        - name: Your Name
          email: your-email@example.com
      urls:
        - https://github.com/your-repo/predixy-redis-proxy/releases/download/v1.1.0/predixy-redis-proxy-1.1.0.tgz
      dependencies: []
      conditions: []
      icons:
        - https://example.com/icon.png
